In [1]:
from sklearn.cluster import KMeans

In [25]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn.preprocessing as Preprocessing
%matplotlib inline

In [3]:
import sys
import musicbrainzngs as m

In [4]:
artist = pd.read_pickle('artist_features.csv').head()

In [5]:
artist

ArtistName           ArtistSortName ArtistType  \
0                    Liars                    Liars      Group   
1          CunninLynguists          CunninLynguists      Group   
2      The Desert Sessions     Desert Sessions, The      Group   
3              Glenn Gould             Gould, Glenn     Person   
4  G. Love & Special Sauce  G. Love & Special Sauce      Group   

                               ArtistID ArtistCountry ArtistLifeBegin  \
0  03098741-08b3-4dd7-b3f6-1b0bfa2c879c            US            2000   
1  69c4cc43-8163-41c5-ac81-30946d27bb69            US         2000-03   
2  7a2e6b55-f149-4e74-be6a-30a1b1a387bb          None         1997-08   
3  7002bf88-1269-4965-a772-4ba1e7a91eaa            CA      1932-09-25   
4  dbf7c761-e332-467b-b4d9-aafe06bbcf8f            US            1992   

  ArtistLifeEnd   ArtistIsni_list       AreaName   AreaSortName AreaISO  \
0          None  0000000107254546  United States  United States      US   
1          None              None  United States  United States      US   
2          None              None           None           None    None   
3    1982-10-04  0000000110269386         Canada         Canada      CA   
4          None  000000009078593X  United States  United States      US   

                                 AreaID BeginAreaName BeginAreaSortName  \
0  489ce91b-6658-3307-9877-795b68554c98      Brooklyn          Brooklyn   
1  489ce91b-6658-3307-9877-795b68554c98          None              None   
2                                  None          None              None   
3  71bbafaa-e825-3e15-8ca9-017dcad1748b       Toronto           Toronto   
4  489ce91b-6658-3307-9877-795b68554c98  Philadelphia      Philadelphia   

                            BeginAreaID  
0  a71b0d32-7752-49e9-8594-2247ad6ac12c  
1                                  None  
2                                  None  
3  74b24e62-d2fe-42d2-9d96-31f2da756c77  
4  0eeb01c2-6e31-46ad-96b8-319749f731d2

In [9]:
X = np.array([[1, 2], [1, 4], [1, 0],
              [4, 2], [4, 4], [4, 0]])
kmeans = KMeans(n_clusters=2, random_state=0).fit(X)
print kmeans.labels_
#array([0, 0, 0, 1, 1, 1], dtype=int32)
print kmeans.predict([[0, 0], [4, 4]])
#array([0, 1], dtype=int32)
print kmeans.cluster_centers_
#array([[ 1.,  2.],
 #      [ 4.,  2.]])


[0 0 0 1 1 1]
[0 1]
[[ 1.  2.]
 [ 4.  2.]]


In [10]:
df_artist_new = pd.read_pickle('artist_features_new.csv')
df_artist_new.shape

(1986, 15)

In [12]:
df_artist_new.head()

ArtistName           ArtistSortName ArtistType  \
0                    Liars                    Liars      Group   
1          CunninLynguists          CunninLynguists      Group   
2      The Desert Sessions     Desert Sessions, The      Group   
3              Glenn Gould             Gould, Glenn     Person   
4  G. Love & Special Sauce  G. Love & Special Sauce      Group   

                               ArtistID ArtistCountry ArtistLifeBegin  \
0  03098741-08b3-4dd7-b3f6-1b0bfa2c879c            US            2000   
1  69c4cc43-8163-41c5-ac81-30946d27bb69            US            2000   
2  7a2e6b55-f149-4e74-be6a-30a1b1a387bb          None            1997   
3  7002bf88-1269-4965-a772-4ba1e7a91eaa            CA            1932   
4  dbf7c761-e332-467b-b4d9-aafe06bbcf8f            US            1992   

  ArtistLifeEnd   ArtistIsni_list       AreaName   AreaSortName AreaISO  \
0          None  0000000107254546  United States  United States      US   
1          None              None  United States  United States      US   
2          None              None           None           None    None   
3    1982-10-04  0000000110269386         Canada         Canada      CA   
4          None  000000009078593X  United States  United States      US   

                                 AreaID BeginAreaName BeginAreaSortName  \
0  489ce91b-6658-3307-9877-795b68554c98      Brooklyn          Brooklyn   
1  489ce91b-6658-3307-9877-795b68554c98          None              None   
2                                  None          None              None   
3  71bbafaa-e825-3e15-8ca9-017dcad1748b       Toronto           Toronto   
4  489ce91b-6658-3307-9877-795b68554c98  Philadelphia      Philadelphia   

                            BeginAreaID  
0  a71b0d32-7752-49e9-8594-2247ad6ac12c  
1                                  None  
2                                  None  
3  74b24e62-d2fe-42d2-9d96-31f2da756c77  
4  0eeb01c2-6e31-46ad-96b8-319749f731d2

In [13]:
def year(s):
    if s != None:
        if s[:3] == '186':
            return '1860'
        elif s[:3] == '190':
            return '1900'
        elif s[:3] == '191':
            return '1910'
        elif s[:3] == '192':
            return '1920'
        elif s[:3] == '193':
            return '1930'
        elif s[:3] == '194':
            return '1940'
        elif s[:3] == '195':
            return '1950'
        elif s[:3] == '196':
            return '1960'
        elif s[:3] == '197':
            return '1970'
        elif s[:3] == '198':
            return '1980'
        elif s[:3] == '199':
            return '1990'
        elif s[:3] == '200':
            return '2000'
        else:
            return s
    else:
        return s

In [14]:
df_artist = df_artist_new.copy()

In [15]:
df_artist['ArtistLifeBegin'] = df_artist.ArtistLifeBegin.apply(year)

In [16]:
df_artist.head()

ArtistName           ArtistSortName ArtistType  \
0                    Liars                    Liars      Group   
1          CunninLynguists          CunninLynguists      Group   
2      The Desert Sessions     Desert Sessions, The      Group   
3              Glenn Gould             Gould, Glenn     Person   
4  G. Love & Special Sauce  G. Love & Special Sauce      Group   

                               ArtistID ArtistCountry ArtistLifeBegin  \
0  03098741-08b3-4dd7-b3f6-1b0bfa2c879c            US            2000   
1  69c4cc43-8163-41c5-ac81-30946d27bb69            US            2000   
2  7a2e6b55-f149-4e74-be6a-30a1b1a387bb          None            1990   
3  7002bf88-1269-4965-a772-4ba1e7a91eaa            CA            1930   
4  dbf7c761-e332-467b-b4d9-aafe06bbcf8f            US            1990   

  ArtistLifeEnd   ArtistIsni_list       AreaName   AreaSortName AreaISO  \
0          None  0000000107254546  United States  United States      US   
1          None              None  United States  United States      US   
2          None              None           None           None    None   
3    1982-10-04  0000000110269386         Canada         Canada      CA   
4          None  000000009078593X  United States  United States      US   

                                 AreaID BeginAreaName BeginAreaSortName  \
0  489ce91b-6658-3307-9877-795b68554c98      Brooklyn          Brooklyn   
1  489ce91b-6658-3307-9877-795b68554c98          None              None   
2                                  None          None              None   
3  71bbafaa-e825-3e15-8ca9-017dcad1748b       Toronto           Toronto   
4  489ce91b-6658-3307-9877-795b68554c98  Philadelphia      Philadelphia   

                            BeginAreaID  
0  a71b0d32-7752-49e9-8594-2247ad6ac12c  
1                                  None  
2                                  None  
3  74b24e62-d2fe-42d2-9d96-31f2da756c77  
4  0eeb01c2-6e31-46ad-96b8-319749f731d2

In [21]:
#one hot coding
new_feature = df_artist[['ArtistType', 'ArtistCountry', 'ArtistLifeBegin']]

In [20]:
#print df_artist['BeginAreaName'].shape
np.unique(df_artist['BeginAreaName'].count(None))

array([1657])

In [22]:
new_feature = new_feature.where((pd.notnull(new_feature)), None)

In [23]:
new_feature.head()

ArtistType ArtistCountry ArtistLifeBegin
0      Group            US            2000
1      Group            US            2000
2      Group          None            1990
3     Person            CA            1930
4      Group            US            1990

In [26]:
# Encode categorical variables using sklearn's one-hot encoder
def encode_categorical(array):
    if not array.dtype == np.dtype('float64'):
        return Preprocessing.LabelEncoder().fit_transform(array) 
    else:
        return array
    
# Categorical columns for use in one-hot encoder
categorical = (new_feature.dtypes.values != np.dtype('float64'))

# Encode all labels
new_feature = new_feature.apply(encode_categorical)

# Get numpy array from data
x = new_feature.as_matrix()

# Apply one hot endcoing
encoder = Preprocessing.OneHotEncoder(categorical_features=categorical, sparse=False)  # Last value in mask is y
x = encoder.fit_transform(x)

In [29]:
x.shape

(1986, 70)

In [30]:
kmeans = KMeans(n_clusters = 100, random_state=0).fit(x)
# print kmeans.labels_
# #array([0, 0, 0, 1, 1, 1], dtype=int32)
# print kmeans.predict([[0, 0], [4, 4]])
# #array([0, 1], dtype=int32)
# print kmeans.cluster_centers_
# #array([[ 1.,  2.],
#  #      [ 4.,  2.]])


In [32]:
kmeans.labels_.shape

(1986,)

In [34]:
kmeans.cluster_centers_.shape

(100, 70)

In [37]:
import random 
random.randint(4)

TypeError: randint() takes exactly 3 arguments (2 given)

In [43]:
random.randint(0,4)

2